### ISSUE TITLE
Ignored Visibility Modifiers (No MIDI-QOL)

### ISSUE THREAD

**Issue by castigo86** [League-of-Foundry-Developers/fvtt-module-lmrtfy#102]
Hy,

running on 0.8.6 and the latest LMRTFY i noticed that the Modifiers Blind Roll, Private Roll and such are ignored. 
Adv and Dis modifiers are honoured by the system instead, they work fine.

I am not running Midi-qol (never installed it). I saw the [Issue posted here](https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/issues/77) but it doesn't seem to be the exact same issue. 

Thanks!

**Comment by castigo86** [comment]
Extra Info: I tested the issue in Safe Mode (with no other modules activated) and the issue is present.

**Comment by vtt-lair** [comment]
I'll have a look at this, it was definitely working for 0.8.5. Thanks for the letting us know
