### ISSUE TITLE
white on white text in Select User drop down

### ISSUE THREAD

**Issue by wmve** [League-of-Foundry-Developers/fvtt-module-lmrtfy#103]
is this white on white text a result of LMRTFY or D35E?

![image](https://user-images.githubusercontent.com/55966777/121950709-fd2dfc00-cd27-11eb-9352-5645918fb51d.png)

the two active modules are 3.5e Loot Sheet and LMRTFY

i realize this is not a huge priority, but deserves some fixing when the update for the code that's responsible rolls around.

**Comment by vtt-lair** [comment]
That's probably D35E, if the theme that you are showing in your screen shot is the standard theme for D35E. What happens if you use the parchment theme of LMRTFY?
