### ISSUE TITLE
PF2e Rolls - Feature Request: Add options for DC and show traits

### ISSUE THREAD

**Issue by Chainsoroth** [League-of-Foundry-Developers/fvtt-module-lmrtfy#104]
Good day! 
When using lmrtfy in PF2e, the rolls are not using the "normal" system rolls.
![image](https://user-images.githubusercontent.com/76947540/122633902-4c36b100-d0db-11eb-995c-394c900ab06c.png)
First roll is the lmrtfy roll, the second one is the "system" roll. (with the traits for wisdom and trained)

Second thing is: PF2e has a built in syntax, to set DCs for a roll and show the GM the results of the roll. (crit fail, fail, success, crit success) (the attack roll is just meant as an example, because I can not call for that in lmrtfy)

**Comment by iBoMbY** [comment]
Have a look at my fork: https://github.com/iBoMbY/fvtt-module-lmrtfy

**Comment by akrigline** [comment]
@iBoMbY if you have a fix for this issue, would you mind opening a PR with it?

**Comment by iBoMbY** [comment]
Sorry, but this is a major modification. The rolls all need specific handling. I see no easy way to integrate this upstream.

**Comment by iBoMbY** [comment]
I mean you probably could add specific path to some of the methods. The rolls for skills, initiative, and perception all come with their own roll method, but for this to work properly you have to supply proper roll options (the DC is optional):

```js
const skill = actor.data.data.skills[skill_id];
const options = actor.getRollOptions(['all', 'skill-check', skill.name]);
skill.roll({ event, options, dc: this.dc });
```

**Comment by vtt-lair** [comment]
I've fixed PF2E compatibility and also included the DC to check against as well as showing the traits. Waiting for the League to release the new version.
