### ISSUE TITLE
Custom Formula

### ISSUE THREAD

**Issue by jseaz73** [League-of-Foundry-Developers/fvtt-module-lmrtfy#119]
I do not use it often, but the feature is helpful for crazy attack ideas the kids have....

Like I grab a chair and hit the brigand with it ...  

It appears when I click the down arrow on the dice& mods for a custom role the CSS gets messed up and chops off Charisma

![image](https://user-images.githubusercontent.com/16529812/134893950-1f798d91-d86a-485b-847d-47e9d9a4a6f8.png)

**Comment by vtt-lair** [comment]
Thanks @jseaz73 will see if I can get it replicated and fixed sometime during the week
