### ISSUE TITLE
Skill checks malfunction

### ISSUE THREAD

**Issue by Arlomagno** [League-of-Foundry-Developers/fvtt-module-lmrtfy#120]
Hello,
when I request skill checks the request pops up but clicking on it does nothing... it's working properly for saves and extras, but not for skill nor ability checks.
I'm running version 1.20 with foundry 0.8.9 and pathfinder 2E 2.14.4.8167.
Thanks

**Comment by vtt-lair** [comment]
@Arlomagno, would it be possible to clear your console on both the user and GM's side and just see if there's an error logged when trying to do the skill check?

And if there is, to just post it here for us.

**Comment by Arlomagno** [comment]
Sure, no problem on GM side, but on player I got

roller.js:142 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at LMRTFYRoller._makeRoll (roller.js:142)
    at LMRTFYRoller._onSkillCheck (roller.js:289)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
_makeRoll @ roller.js:142
_onSkillCheck @ roller.js:289
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by vtt-lair** [comment]
Thanks. I wonder if something changed recently on PF2e system with regards to the actor and roll method.

**Comment by vtt-lair** [comment]
I do see there was a new release 2 days ago. Could be something changed in the system that's causing this.

**Comment by vtt-lair** [comment]
I have loaded an issue on PF2E to see if one of their developers can point us in the correct direction. Issue is: https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/issues/1762

**Comment by vtt-lair** [comment]
I've fixed PF2E compatibility and also included the DC to check against. Waiting for the League to release the new version.

**Comment by Arlomagno** [comment]
Awesome! Thanx!

**Comment by llothos** [comment]
I just installed this module again and running it with PF2E and I can't get the skill checks to work. It pops up for players but clicking roll does nothing. Things like saves work but not skills. This is the Error code:

roller.js:187 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'skills')
    at LMRTFYRoller._makeRoll (roller.js:187:61)
    at LMRTFYRoller._onSkillCheck (roller.js:400:14)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
_makeRoll @ roller.js:187
_onSkillCheck @ roller.js:400
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
