### ISSUE TITLE
Blind Rolls Not Blind - showing to all players

### ISSUE THREAD

**Issue by azarius74** [League-of-Foundry-Developers/fvtt-module-lmrtfy#128]
I've installed LMRTFY (1.20) on Foundry (.8.9) and when I request a blind roll from the PC, he sees the dice roll.   If I change the MODIFIERS from "Normal Roll" to "Query Player" - he does NOT see the roll, and I do.  Is this normal function?

Also - If I have three players logged in, and send a GM roll to a player, ALL players still see the roll (if roll type is set to "Normal Roll")

**Comment by KammaKhazi** [comment]
I've been experiencing these issues myself lately (previously it was fine). I use midi-qol  and dice so nice also (latest version) with ghost rolls set. But in testing last Sunday my players were able to see private/blind/self rolls. I tried both using the LMRTFY GUI and also via a macro.

**Comment by azarius74** [comment]
Tim (@ Midi-QOL) was able to figure out the issue - apparently there was a delay between LMRTFY and Midi-QOL when hosting on the Forge that let the LMRTFY push the roll through before midi-QOL could intercept it.   A new patch was pushed out this morning, and I can confirm that it does indeed now work as intended!
