### ISSUE TITLE
v9 - controlled tokens not populated

### ISSUE THREAD

**Issue by BladeFireLight** [League-of-Foundry-Developers/fvtt-module-lmrtfy#130]
this might be a v9 issue. but I do not see the list of tokens to select a request for. 
![image](https://user-images.githubusercontent.com/8352828/147419799-b333733a-4d68-4c55-bea7-a3ffb627cb78.png)

**Comment by nirurin** [comment]
Came here to say the same thing. The automated roll requests via midiQOL seem to still work fine, but you can't set up a manual roll request in V9 it seems.

**Comment by vtt-lair** [comment]
Noticed this myself last night. Will have a look at this over the weekend. Thanks for pointing it out!
