### ISSUE TITLE
Game Master macros don't work

### ISSUE THREAD

**Issue by ilore** [League-of-Foundry-Developers/fvtt-module-lmrtfy#138]
I'm using 3.5e SRD system, Foundry V9 and I have all modules up to date. When I create a macro in order to request rolls from the Game Master, it doesn't work (the console doesn't even show error messages).

**Comment by p4535992** [comment]
can you show us the macro you are trying to use ?

**Comment by vtt-lair** [comment]
Please check again with the next release.
