### ISSUE TITLE
Rollable Table Function doesn't let you open journals

### ISSUE THREAD

**Issue by Fyrexian** [League-of-Foundry-Developers/fvtt-module-lmrtfy#141]
When someone draws from the Rollable table function in this module, it doesn't let you open them (permissions are owner for everyone).
Even the GM can't open them, but people can open them when you roll it normally from the foundry's default system.

FVT 9 242
PF2E 3.2.2.10109
LMRTFY 1.25

**Comment by vtt-lair** [comment]
This will be fixed in the next release. Sorry for taking so long
