### ISSUE TITLE
Feature Request: Ability to open the roll requester form a macro

### ISSUE THREAD

**Issue by tposney** [League-of-Foundry-Developers/fvtt-module-lmrtfy#152]
Could an entry point that programs could call to open the roll requester window be added?
Something like
```js
globalThis.LMRTFYRequestRoll = LMRTFY.requestRoll;
```
added to lmrtfy.js

**Comment by vtt-lair** [comment]
@tposney Sorry I took so long in replying Tim. I moved to a different country in a different hemisphere end of February and life has just been crazy.

I've added the entry point to lmrtfy.js and it'll be available in the next version, which unfortunately will also be an only v10 update.
