### ISSUE TITLE
Requesting a roll from selected token

### ISSUE THREAD

**Issue by bringthebam** [League-of-Foundry-Developers/fvtt-module-lmrtfy#158]
Would it be possible for the GM to set macros instead for a defined token, but to the current selected or targeted token?
Right now if I try to create a macro without a Character, it replies with "LMRTFY: Nothing to request"

Use case:
Needing to ask for stealth, or survival checks from different party members one at each time.

**Comment by vtt-lair** [comment]
This will be released in the next version. Unfortunately the next version will be the upgrade to version 10 too. So once all your other modules are v10 stable, you'll have the functionality.

I've added a new option in the dropdown list, that will allow only saving of a macro and will specify that a token has to be selected when the macro is run, as those tokens will be used:
![image](https://user-images.githubusercontent.com/33215552/188235993-6201ef2d-74c8-4899-aa8e-7e6d87fdf281.png)
