### ISSUE TITLE
No window opening up, not working. 

### ISSUE THREAD

**Issue by Ainasul** [League-of-Foundry-Developers/fvtt-module-lmrtfy#164]
Just installed and the window does not open when pressing the dice icon. 

FoundryVTT version 10 build 285
Dnd 5e version 2.0.0 

I disabled all modules except LMRTFY and it still does not open a window. 
I had one player logged in.

**Comment by dd2465** [comment]
I am having the same issue. Clicking the dice icon does nothing. Orange border lights up but no windows pop up to request a roll.

**Comment by DetectiveTimy** [comment]
Same problem here, nothing happen when I click the button.

**Comment by Varriount** [comment]
This module has not been ported to Foundry V10. Is Foundry not showing a warning regarding this module?

**Comment by vtt-lair** [comment]
@Varriount was ported to version 10 with release 3.0.2

@Ainasul, @dd2465, @DetectiveTimy can you open the console and see if there's any error shown when clicking ont he dice icon?

**Comment by vtt-lair** [comment]
I think there was a change between 284 and 285 with regards to how the localize was being done. Busy investigating the issue and should have a fix up a bit later today

**Comment by vtt-lair** [comment]
OK. Issue is not with the localize but with a change to the DND system and the way they changed the skills config. Previously it was a straight string, now they are using a more complex json structure to define the skills.

Fix shouldn't be to big of an change, however unsure how the fix will interact with other systems.

Will think about it a bit.
