### ISSUE TITLE
Query Player Modifier option fails to roll properly.

### ISSUE THREAD

**Issue by szefo09** [League-of-Foundry-Developers/fvtt-module-lmrtfy#172]
Seems to be related to PR #171 , If you ask for a roll with modifier Query Player, you'll get a request that will not add any bonuses to the roll and the roll will be requested twice.
![image](https://user-images.githubusercontent.com/37833135/214722202-aeb4d0ce-8b01-44c4-b307-1a4ff6ace6fb.png)

**Comment by szefo09** [comment]
Found a culprit of double prompt, it's Line 510, which I believe should have been removed when adding new Midi Roller.
https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/blob/6d77fd3b353262f7454568de09eab76f6e41bf66/src/roller.js#L506-L520

And the culprit of Query Player no modifier should be Line 244, assigning event to option. 
https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/blob/6d77fd3b353262f7454568de09eab76f6e41bf66/src/roller.js#L231-L246

**Comment by GambetTV** [comment]
Double Prompt occurs for all saving throws, even not ones requested by MidiQOL, but through the normal LMRTFY menu prompt.

**Comment by vtt-lair** [comment]
I've fixed the double prompt and that has just been released, will have a look at the other issue and hope to have a fix released later tonight

**Comment by vtt-lair** [comment]
Ok, Fixed the query player issue and will release a fix for in the next hour
