### ISSUE TITLE
Request: Please allow us to disable the "FAIL" option.

### ISSUE THREAD

**Issue by GambetTV** [League-of-Foundry-Developers/fvtt-module-lmrtfy#173]
I genuinely don't understand the use case for this for DnD5e, and it is very clunkily implemented. The whole purpose of this module, I thought, was to simplify rolling for players to avoid the "Where do I click?" conversation from new players, and then also to supplement MidiQOL in a very awesome way.

But now every roll prompt has two buttons, one of which (the FAIL button) is grayed out unless you click on the much smaller dice icon. If you do that, it disables the normal option unless you click on the dice icon on the FAIL option again, which is just very unintuitive. And best case scenario when this works perfectly is that it very obviously drops a -100 into the roll field, something that the player could easily add themselves with the normal prompt that includes the Situational Bonus. 

Anyway I just feel like it unnecessarily complicates things, and clutters up the screen prompt for no real benefit, and I'd like to request a settings option to disable this extra FAIL button.

**Comment by vtt-lair** [comment]
The specific use case was if a spell is cast on a player by another player (like Vortex Warp or Polymorph), to give the player the ability to fail that check (as the spell specifies a target can choose to fail) without having to manually enter an extra value.

Further to this, I know for instance Midi-Qol gives you the ability to use LMRTFY for spells and also has the ability to just use LMRTFY without the "Query" section. So in those cases the player won't be able to manually set the value.

I also didn't want the ability to accidently click the FAIL button when you don't want to, as such the button is disabled until you enable it.

Will see to implementing an option that allows you to show or not show it.

Would you like this option to be on the form Requestor (where you request the rolls) or would you like to rather have it as an option on the module settings @GambetTV

**Comment by vtt-lair** [comment]
Also, if you feel it's too cluttered, I can see about moving it next to the normal button as opposed to under it. Make it a much smaller button.

Something like this:
![image](https://user-images.githubusercontent.com/33215552/215865728-8f5099f3-d67c-4c66-97b7-ffa2f51f3eb4.png)

Then maybe do away with the toggle (enable/disable) functionality?

**Comment by GambetTV** [comment]
I do like the smaller Fail button *better*, but IMHO I'd probably still just like the option to disable it in the module settings. 

I appreciate where you're coming from on this, but my experience largely has been that players can fail the rolls themselves just by typing -100 into the situational modifier field that pops up anyway, and so we're not saving a whole lot of time even if they use it optimally, and instead the extra button just kind of confuses things for them, and takes extra time to explain it to them.

Admittedly people who play with the same four or five players week after week might not have much of an issue here, but anyone who plays with lots of players and runs multiple games (like me) might find that they just have to explain it over and over and over again.

That said, the picture you just posted with the fail button on the right makes it a LOT BETTER. So maybe do both? Put it on the side so that it seems less important, but also give GM's the option to just disable it completely?

**Comment by vtt-lair** [comment]
I'll implement both solutions. will just have to do some style juggling. :)

Will add an option in module settings.
And change the button styling.

Will see if I can spend some time at the end of the week to sort this out.

**Comment by vtt-lair** [comment]
I've added the ability to disable the fail button so that it doesn't show. It's defaulted to show the button, so you can just disable it. I'll work on a solution to make it look better at a later stage... with the hide/show setting it make styling a bit more difficult and don't have the capacity to sort that out right now.

At least you have the button to hide them if you don't want to use it :)
