### ISSUE TITLE
Module not working on DnD v2.2.1

### ISSUE THREAD

**Issue by KammaKhazi** [League-of-Foundry-Developers/fvtt-module-lmrtfy#184]
Clicking to bring up the UI and making LMRTFY rolls via midi doesn't do anything on DnD v2.2.1, Foundry v10.291
kind regards and thank you for your hard work.

**Comment by MrVizious** [comment]
Doesn't work on Dnd v2.2.0 either, Foundry v10.291 as well.
Here is a capture of the error:
![image](https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/assets/38861496/4bafc39f-3587-4399-8f84-634e8f3a3002)

**Comment by rafacrudi** [comment]
Using v3.1.7, looks like it's working again.

**Comment by M0nk3yy** [comment]
> Using v3.1.7, looks like it's working again.

If you are using MidiQoL then it's probably because Midi included a temporary patch until LMRTFY is updated.

**Comment by rafacrudi** [comment]
That's probably it, thank you @M0nk3yy !

**Comment by matthewbstroud** [comment]
When will this be pushed in a release?
