### ISSUE TITLE
LMRTFY is no longer coming up. Help!

### ISSUE THREAD

**Issue by mussja28** [League-of-Foundry-Developers/fvtt-module-lmrtfy#187]
Went to test this as I'm leading up to getting my group changed over from Roll20 to Foundry VTT and it worked when I initially installed it, but now it's not working and I'm not to fluent with the error text to know what's happening. So hoping someone can see the error text when I try to use it to help me figure this out.

![image](https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/assets/137832669/ca9ba1db-d199-48c8-9066-98976755e22d)

**Comment by mussja28** [comment]
Can confirm that disabling all of the mods and loading just this one didn't change anything.

**Comment by matthewbstroud** [comment]
I get the same thing.

**Comment by matthewbstroud** [comment]
CONFIG.DND5E.abilities has been changed to an object. The former value can be acccessed from .label

**Comment by matthewbstroud** [comment]
This should be really easy to fix.

**Comment by matthewbstroud** [comment]
The fix from this PR is _**not**_ in the zip file for the current release.

**Comment by mussja28** [comment]
So the fix is out there, just not in the zip file that comes with the download. Not sure I quite follow, sorry.

**Comment by matthewbstroud** [comment]
No one created a new release.  The fix is in pull request 185.  The latest
release only goes to 181.

**Comment by mussja28** [comment]
Perfect thank you I got it! Just updating Midi QoL did the trick! Thanks for clarifying and pointing me in the right direction!
