### ISSUE TITLE
Request - Play a tiny bell sound for the player asked to roll.

### ISSUE THREAD

**Issue by TheAtrivion** [League-of-Foundry-Developers/fvtt-module-lmrtfy#33]
Just found this module while trying to figure out how to write macros for rolling a check with disadvantage. Now i dont need to anymore and that makes me happy!

I do have a small request, would it be possible to add a small bell sound or a sound you pick from your audio list for the player when that player is asked to roll, just to draw attention to the screen? Preferably not all players just the one asked to roll.
Or would it be easy for me to add that to the macro this module creates without breaking said macro?

**Comment by kakaroto** [comment]
I don't think you could add it to the macro, at least, not if you want it to just play for the specific user you're sending to (if you're ok with the sound playing for everyone, check out one of the macros in the furnace compendium, I believe I have one for play sound in there).

I'm a little unsure of this feature, I don't think it's a necessary addition, though it would be nice, I'm also lacking the time to actually add it (as evidenced by how long it took to reply).
So... I'm unsure at the moment, but I'm keeping this open for when I get to it and I'll re-evaluate.
Thanks.

**Comment by akrigline** [comment]
I'm not really keen on adding more moving parts to this relatively simple module, sorry.
