### ISSUE TITLE
When initiative is requested, make the result the initiative in the combat tracker

### ISSUE THREAD

**Issue by wesbaker** [League-of-Foundry-Developers/fvtt-module-lmrtfy#34]
There's totally a chance I'm doing this wrong, but I'm requesting an initiative roll and it's not setting their initiative in the current combat. Ideally, when a player rolls initiative it would set that score in the combat tracker.

**Comment by kakaroto** [comment]
Ideally the dnd5e actor would have a way to roll initiative, unfortunately it doesn't, so we have to roll it manually. This is why it's not adding it to the tracker.
I need to file an issue with the dnd5e system so this can get fixed.
Thanks

**Comment by akrigline** [comment]
I think this is possible now. I'll take a look.

`this.actor.rollInitiative` might be the ticket.

**Comment by akrigline** [comment]
Coming Soon :tm:
