### ISSUE TITLE
Add Translate French

### ISSUE THREAD

**Issue by Elfenduil** [League-of-Foundry-Developers/fvtt-module-lmrtfy#45]
Hello

Hello

Can you add the translation in a future update?

Thank you

See Attachment file

[FR LMRTFY.txt](https://github.com/kakaroto/fvtt-module-lmrtfy/files/5801110/FR.LMRTFY.txt)

**Comment by akrigline** [comment]
Could you do me a favor and open a pull request with the translations in the correct JSON file? You can see how to set it up by looking at this Pull Request's differences:

https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/pull/48

**Comment by Elfenduil** [comment]
Hello,

I'll like but i'm a newby with Github, i try to create a new pull request but i don't know ...

**Comment by akrigline** [comment]
PR Merged, thanks! Coming in 1.7
