### ISSUE TITLE
Enhancement request - plug result of roll into a table.

### ISSUE THREAD

**Issue by jccraig26** [League-of-Foundry-Developers/fvtt-module-lmrtfy#57]
Not sure if this is feasible for you to do.  But, I was trying to find a way to take the result of the roll from the player - for example let's say just a 1d20.  Instead of emitting that to the chat - blind or public,  feed that number into a selected table and THEN emit the results from the table.  

I thought adding the option for an additional step would make it even more versatile.

**Comment by akrigline** [comment]
With the most recent update, you can request that a player roll from a rollable table. If I understand you right that's what you're trying to acheive?

**Comment by akrigline** [comment]
Going to close this, feel free to reopen if the rollable table request isn't what you were looking for.
