### ISSUE TITLE
Sort the Skill List on the Sender side by Alpha after Localization

### ISSUE THREAD

**Issue by akrigline** [League-of-Foundry-Developers/fvtt-module-lmrtfy#58]
It would be ideal to sort the skill checks list in the request application by Alpha after localization. Currently there is logic to sort the skill checks in the Roller application but not the requester.

@akrigline The issue is still present in 1.8 despite #51 
![image](https://user-images.githubusercontent.com/18719694/107559316-39b3e480-6bdc-11eb-990d-bbf91b3ba9bd.png)

_Originally posted by @santalucial in https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/issues/42#issuecomment-776944597_

**Comment by santalucial** [comment]
this is already solved by #42 tho there might be better way to handle it with the handlebar lib that i'm unaware of

**Comment by akrigline** [comment]
I'm pretty sure that this can be accomplished in the same mechanism by which #51 worked, but I just forgot that the same changes needed to happen to `LMRTFYRequestor`. This is the perfect use case for [`localeCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) and [`Array.sort`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort).

**Comment by akrigline** [comment]
hopefully resolved in 1.9
