### ISSUE TITLE
It's unclear what rulesystems lmrtfy works with

### ISSUE THREAD

**Issue by Heilemann** [League-of-Foundry-Developers/fvtt-module-lmrtfy#59]
I'm running WFRP4e, and as far as I can tell lmrtfy doesn't work with it. I've installed it, but it doesn't show up anywhere. Would be nice if there was at least a list of system it does or doesn't work with.

**Comment by akrigline** [comment]
The readme should definitely include this. Thanks for the feedback!

**Comment by Heilemann** [comment]
(I'd also take WFRP support, of course 😄)

**Comment by davidthegnome** [comment]
And Savage Worlds please and thank you :)

**Comment by akrigline** [comment]
Added list of systems currently supported to the readme.

I've also added documentation about how to add support for other systems in the [CONTRIBUTING](https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/blob/master/CONTRIBUTING.md) docs. I don't play anything but dnd5e but I'm happy to merge this kind of PR.
