### ISSUE TITLE
Enhancement request - Savage Worlds Adventure Edition compatibility 

### ISSUE THREAD

**Issue by davidthegnome** [League-of-Foundry-Developers/fvtt-module-lmrtfy#60]
Please make you awesome mod even more awesome by adding Savage Worlds support.

**Comment by akrigline** [comment]
I've just added documentation about how to add support for other systems in the [CONTRIBUTING](https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/blob/master/CONTRIBUTING.md) docs. I don't play anything but dnd5e but I'm happy to merge this kind of PR.
