### ISSUE TITLE
PF1e support?

### ISSUE THREAD

**Issue by dmrickey** [League-of-Foundry-Developers/fvtt-module-lmrtfy#64]
It would be nice if this supported PF1e

**Comment by akrigline** [comment]
I've just added documentation about how to add support for other systems in the [CONTRIBUTING](https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/blob/master/CONTRIBUTING.md) docs. I don't play anything but dnd5e but I'm happy to merge this kind of PR.

**Comment by dmrickey** [comment]
Awesome, it looks pretty straightforward. Thanks for adding that documentation

**Comment by akrigline** [comment]
@ManaHime has just provided #72 which accomplishes this! 
Released in 1.13
