### ISSUE TITLE
Support for The One Ring v1

### ISSUE THREAD

**Issue by herveDarritchon** [League-of-Foundry-Developers/fvtt-module-lmrtfy#68]
hi !

I am the creator of the of the [system for The One Ring v1](https://gitlab.com/herve.darritchon/foundryvtt-tor1e/-/issues/85). I am planning, as a user asked me, to be compatible to your module (should say the opposite I guess as it is a PR in your module if I have understood correctly ;) ).

I want to know if you are still open to PR and I wanted to log this issue to have a support for chating because I have to admit I [didn't understood all](https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/blob/master/CONTRIBUTING.md) I have to do to make this work fine ;)

===========================================================================================

- [X] I know what to do
- [ ] I am a bit lost

--------

- [X] 1. Add your system to the module.json 

- [ ] 2. Add system definitions to LMRTFY#ready

  - [X] I have to create a new case for my system
  - [] which method on the Actor class can roll the appropriate check?
    - I don't understand what I have to put in this list
  - [] where are the abilities, skills, and saves defined?
    - I don't understand what I have to put either

- [ ] 3. (Maybe Optional) Check LMRTFYRoller#_makeRoll signature
  - I am quite lost
  
- [X] 4. Open a PR

**Comment by akrigline** [comment]
I took a quick look at the system code and I also am quite lost. I don't think LMRTFY will be compatible with how your system is set up. It makes assumptions that don't seem to be true for your case.

LMRTFY assumes there is a js class for `Actor` that has methods on it which control rolling the ability checks/saves. I didn't look super hard but it looks like your system's entities aren't set up like that.

Sorry I'm not much more help than that, I'm really just keeping this running in maintenance mode.

**Comment by herveDarritchon** [comment]
wouaaaah great, that was the exact exchange I wanted. It helps a lot.

I can help you in my code ;) this is the least I can do :D

All my Actors are in this directory : https://gitlab.com/herve.darritchon/foundryvtt-tor1e/-/tree/develop/src/modules/sheets/actors

Right now, I have 3 types of Actors : 

- Character --> PC
- Adversary --> Monsters
- NonPlayerCharacter --> NPC

I import in these Actors an utilities file : `{tor1eUtilities} from "../../utilities.js"`

https://gitlab.com/herve.darritchon/foundryvtt-tor1e/-/blob/develop/src/modules/utilities.js

This is where I set up Roll code like : 

```js
/**
     * Update the value of a stat when you change the value in the input text box.
     * Should be used for example when an item is in a sheet because the object doesn't belong to the proper stat of the sheet.
     * @param extra
     * @param event
     * @returns {*}
     */
    "onItemName": function (extra = {}, event) {
        event.preventDefault();
        let element = event.currentTarget;

        if (event.altKey) {
            let itemId = _getItemId(event);
            let item = this.actor.getOwnedItem(itemId);
            let field = element.dataset.actionFavouredName;

            let value = element.dataset.actionFavouredValue === "true";
            return item.update({[field]: !value});
        } else {
            let automaticDifficultyRoll = !event.shiftKey;
            Dice.taskCheck({
                actor: this.actor,
                user: game.user,
                askForOptions: automaticDifficultyRoll,
                actionValue: element.dataset.actionValue,
                actionName: element.dataset.actionName,
                wearyRoll: this.actor.data.data.stateOfHealth.weary.value,
                modifier: _getModifier(element, extra),
                shadowServant: extra.shadowServant,
            });
        }
    },
````

The `Dice.taskCheck` rolls the dice. It is the file https://gitlab.com/herve.darritchon/foundryvtt-tor1e/-/raw/develop/src/modules/sheets/dice.js

Right now in my System, all the checks are generic, what I supposed is that your module expect a more specific approach ? Like each roll is in  the actor class with a method, the one I put in the `2. Add system definitions` ?

**Comment by akrigline** [comment]
> what I supposed is that your module expect a more specific approach ? Like each roll is in the actor class with a method, the one I put in the 2. Add system definitions ?

Correct. with what I see and what you've shared, I don't think your system will work with LMRTFY. I at least do not know how to make it work.
