### ISSUE TITLE
Death Saving Throws incorrectly roll "Death Savings Throw"

### ISSUE THREAD

**Issue by shinkei13** [League-of-Foundry-Developers/fvtt-module-lmrtfy#69]
**Feedback Type**: Bug

**Core**: 0.7.9
**System**: dnd5e v1.2.4
**Module Version**: lmrtfy v1.11

At current, whenever a PC is called on to roll a Death Saving Throw, it incorrectly calls for a "Death Savings Throw" instead of a proper Death Saving Throw. (Picture Attached)

<p><img width="287" alt="Screen Shot 2021-03-13 at 4 26 05 PM" src="https://user-images.githubusercontent.com/33383758/111052028-12d81080-841d-11eb-8c6e-f4b962ef7050.png">
<br><i>The top roll is generated by LMRTFY, whereas the bottom is rolled using the character sheet.</i></p>

In addition, the attributes `attributes.death.success` and `attributes.death.failure` do not update properly.

**Comment by shinkei13** [comment]
I was able to fix it on a personal copy of LMRTFY by replacing lines 287-290 of roller.js:
`    _onDeathSave(event) {
        event.preventDefault();
        this._makeDiceRoll(event, "1d20", game.i18n.localize("LMRTFY.DeathSaveRollMessage"));
    }
`
with the following:
`_onDeathSave(event) {
        event.preventDefault();
        if(game.system.id == "dnd5e") {
            for (let actor of this.actors) {
                actor.rollDeathSave(event);
            }
            event.currentTarget.disabled = true;
            if (this.element.find("button").filter((i, e) => !e.disabled).length === 0)
                this.close();
        } else {
            this._makeDiceRoll(event, "1d20", game.i18n.localize("LMRTFY.DeathSaveRollMessage"));
        }
    }`

**Comment by akrigline** [comment]
@shinkei13 thanks for your in depth report! Are you willing to open a PR making this change? If so I'm happy to merge it and can get a release pushed out with this fix sooner than I will otherwise get to this change.

**Comment by shinkei13** [comment]
> @shinkei13 thanks for your in depth report! Are you willing to open a PR making this change? If so I'm happy to merge it and can get a release pushed out with this fix sooner than I will otherwise get to this change.

Just did! Happy to help. Long time user of LMRTFY, so anything I can do to give back, I will!
