### ISSUE TITLE
Doesn't Roll

### ISSUE THREAD

**Issue by Zemfreed** [League-of-Foundry-Developers/fvtt-module-lmrtfy#75]
Click on request roll and player gets the dialog box, click on button and nothing happens. Dialog box stays on players screen and no roll is submitted to the GM.
Currently PF1E 0.77.16, Foundry VTT 0.7.9 
Actually Private Rolls.
Active Modules
Adjusted Movement
FXMaster
Grid Scale Menu
Multilevel Tokens
PopOut!
sbc|PF1 Stackblock Converter
Smart Doors
Trigger Happy

**Comment by akrigline** [comment]
@Zemfreed can you provide some step by step reproduction steps for this?

What exactly reproduces this issue?

@ManaHime if you get a chance can you take a look at this?

**Comment by ManaHime** [comment]
I will take a look however the current version of pf1e is 0.77.19 and the version I originally tested was 0.77.18 therefore I would like to ask if updating might fix this?
@Zemfreed please le me know if your players are experiencing any error in the console (f12 on foundry and then console tab)

**Comment by Zemfreed** [comment]
@ManaHime Thanks for the quick response and I'm really sorry :( I didn't realize there had been a update to PF1. After updating it, it works as expected. 
Again Sorry for the mixup.

**Comment by akrigline** [comment]
Awesome, thanks @ManaHime and @Zemfreed for following up!
