### ISSUE TITLE
Issue with LMRTFY, Midi-qol and Magic Resistance 

### ISSUE THREAD

**Issue by nulmas** [League-of-Foundry-Developers/fvtt-module-lmrtfy#76]
Saving throws sent by midi-qol through Let Me Roll That For You (and I suppose other types of advantage) will be rolled as normal rolls. The keyboard shortcuts are set to default in midi-qol.

The card still identifies the roll as if it had been made with advantage, and if you wait until the automatic roll kicks in, it will be with advantage.

I'm pretty sure this was working ok when I first tried it, because I remember changing the shortcuts and that making LMRTFY behave oddly, but I may be misremembering.

I crossposted this to midi-qol's gitlab: https://gitlab.com/tposney/midi-qol/-/issues/317

**Comment by vtt-lair** [comment]
As far as I understand Tim from midi-qol patch this last year. Please let me know if it's still an issue.
