### ISSUE TITLE
LMTFY Modifier options are not honored together with midi-qol

### ISSUE THREAD

**Issue by Tupsi** [League-of-Foundry-Developers/fvtt-module-lmrtfy#77]
When midi-qol ist active the Modifier Options in LMRTFY are ignored. No matter what you put there ("Normal, Adv, Dis, Query") you always end up with the normal query window after clicking the LMRTFY gui button.

Steps to reproduce:

1) have LMRTFY and MIDI-QOL active
2) Log in a GM and a player
3) let the GM request any roll with Advantage Modfier selected
4) Player will get the request and the text is even saying it is an adv roll, but if you click on the button, you get the normal query window with the standard "Dis, Norm, Adv" buttons as well and only what you click there is honored and rolled.
5) deactivate MIDI and repeat 3, now whatever you select there will be used when you execute on the player side.

I am putting that on both your issue list, as I have no clue which of you have todo anything to make it work together, but would be awesome if you can figure that out! :-)
https://gitlab.com/tposney/midi-qol/-/issues/321

![lmrtfy_option](https://user-images.githubusercontent.com/3730499/113588477-7a563a00-9630-11eb-96dd-61f5248e8e4f.jpg)

**Comment by kimitsu** [comment]
Not sure if intended as such, but the solution seems to be to set the "Prompt players to Roll Saves" setting to "LMRTFY + Query" in midi-qol settings.

**Comment by Tupsi** [comment]
> Not sure if intended as such, but the solution seems to be to set the "Prompt players to Roll Saves" setting to "LMRTFY + Query" in midi-qol settings.

so you wrote that here as well, so I really have to ask; 

did you even try what you wrote?

But to iterate here as well; I am trying to MANUALLY GM REQUEST A ROLL, which should have nothing todo with anyone has setup inside midi, as this is not from something inside a midi/combat/spell workflow, but just a simple roll requested by the gui.

**Comment by Tupsi** [comment]
@kimitsu what you wrote over at midi-qols [issue](https://gitlab.com/tposney/midi-qol/-/issues/321) post is a nice workaround, thank you!

**Comment by vtt-lair** [comment]
As far as I understand Tim from midi-qol patch this last year. Please let me know if it's still an issue.
