### ISSUE TITLE
foundry 0.8.2 compatibility for midi-qol

### ISSUE THREAD

**Issue by tposney** [League-of-Foundry-Developers/fvtt-module-lmrtfy#94]
LMRTFY has a special case addition for midi-qol _tagMessage which needs to be updated for 0.8.x to

```
_tagMessage(candidate, data, options) {
    setProperty(data, "flags.lmrtfy", {"message": this.data.message, "data": this.data.attach});
}
```
No big deal but thought I'd flag it since I noticed it.

**Comment by tposney** [comment]
Turns out that for 0.8.4+ the change needs to be:
```
export function _tagMessage(candidate, data, options) {
  let update = {flags: {lmrtfy: {"message": this.data.message, "data": this.data.attach}}};
  candidate.data.update(update);
}
```

**Comment by vtt-lair** [comment]
@tposney, what would be the candidate parameter be? Meaning what would be expected there. I see currently it's just binding the _tagMessage, sending through this as a parameter.

Would that still stay the same when you set the Hook? Or would something have to change there as well?

I'm busy fixing the roll tables implementation for 0.8.x and saw your issue. Thought I might tackle this while I'm busy with my own stuff.

**Comment by tposney** [comment]
The preCreate hooks signature has changed, it passes the (candidate, data,
options, user), where candidate is the to be created entity.
Sinc the Hook.on is just
Hooks.on("preCreateMessage", this._tagMessage.bind(this))
which does not pass this to the function, it makes _tagMessage have a
sensible value for this. (although under the hood you are right it
is setting the first hidden argument to this), but when called the rest of
the arguments get passed through.
Since all of the arguments are passed through, that's all the change that
is required.

**Comment by tposney** [comment]
Forgot to mention, that since midi-qol is the module that this was inserted
for, I already have a run time patch to make the change and it works.
