### ISSUE TITLE
Update Error on Foundry 0.8.6

### ISSUE THREAD

**Issue by castigo86** [League-of-Foundry-Developers/fvtt-module-lmrtfy#99]
Hy!

When updating the module in Foundry an error is returned by the add-on module manager:

"cannot read property version of 'undefined' ".

![Cattura](https://user-images.githubusercontent.com/84322922/121517465-b078b700-c9ef-11eb-866d-897e991601b5.JPG)

**Comment by GabrielOsvair** [comment]
Hi, I'm also not able to update to v1.15

**Comment by akrigline** [comment]
I believe I've fixed this.
